username_locator = "id=usernameOrEmailAddress"
password_locator = "id=Password"
btn_login_locator = "id=LoginButton"
user_icon_locator = "id=s2-user-icon"
loader_icon_locator = "Xpath=//div[@class='loader' and @style='display: none;']"
bnt_context_menu = "id=button-menu-context"
txt_search = "id=search-grid"
data_table_row = "(//table[@role='grid'])[2]//tr"
logout_button="id=logout"
